NuntiusConfig/Controllers/WorkTimesController.cs
using NuntiusConfig.Models;
using OPCConfigModel;
using OPCConfigModel.Model;
using System;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NuntiusConfig.Controllers
{
    public class WorkTimesController: Controller
    {
        // GET: WorkTimes
        public ActionResult Index()
        {
            return View( new WorkTimesModel() );
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details( Int32 id )
        {
            try
            {

                WorkTimeMVC work_time = null;

                if( id != 0 )
                {
                    work_time = WorkTimeMVC.CreateFromBBDD( id );
                }
                else
                {
                    work_time = new WorkTimeMVC()
                    {
                        WeekDays = new WeekDayModel(WorkTime.WeekDays_DefaultValue)
                    };
                }

                return PartialView( work_time );
            }
            catch( Exception ex )
            {
                TempData["ErrorModel"] = new ErrorModel( ex );
                return RedirectToAction( "Index", "Error" );
            }
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="workTime"></param>
        /// <returns></returns>
        public HttpStatusCodeResult UpdateWorkTime( WorkTimeMVC workTime )
        {
            try
            {

                workTime.SaveToBBDD();

                Session["NeedRestartService"] = true;

                return new HttpStatusCodeResult(HttpStatusCode.OK); 
            }
            catch( Exception ex )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, ex.Message ); 
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public HttpStatusCodeResult DeleteWorkTimeById( Int32 id )
        {
            try
            {
                WorkTimeMVC.DeleteWorkTimeById( id );

                Session["NeedRestartService"] = true;

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch( Exception ex )
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }
        }
    }
}

NuntiusConfig/Views/WorkTimes/Details.cshtml
@model NuntiusConfig.Models.WorkTimeMVC

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>


@{Html.EnableClientValidation(true);}


@using (Ajax.BeginForm("UpdateWorkTime", "WorkTimes",
                    new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccessDetails", OnFailure = "OnFailureDetails" }))
{
    @Html.AntiForgeryToken()


    <div class="modal-content">
        <div class="modal-header">
            <h4>Work time</h4>
            <button class="close" data-dismiss="modal" area-hidden="true">X</button>

        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.Id)

                <div class="editor-label">
                    <dt>Name:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    <dt>Start time:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.StartTime)
                    @Html.ValidationMessageFor(model => model.StartTime)
                </div>

                <div class="editor-label">
                    <dt>End time:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.EndTime)
                    @Html.ValidationMessageFor(model => model.EndTime)
                </div>

                <div class="editor-label">
                    <dt>Week days:</dt>
                </div>
                <div class="editor-field">
                    @Html.CheckBoxListFor( model => model.WeekDays.PostedDays,
                                           model => model.WeekDays.AllDays,
                                           entity => entity.Value,
                                           entity => entity.Text,
                                           model => model.WeekDays.SelectedDays,
                                           MvcCheckBoxList.Model.Position.Vertical )
                </div>

            </dl>
            <div class="modal-footer">
                <p><input type="submit" value="Save" /></p>
            </div>
        </div>
    </div>
}

NuntiusConfig/Views/WorkTimes/Index.cshtml
@model NuntiusConfig.Models.WorkTimesModel

@{
}

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
<link rel="stylesheet" href="~/Content/bootstrap.min.css">
<script src="~/Scripts/bootstrap.min.js"></script>


<script type="text/javascript">

    function OnSuccessDetails(data) {

        $('#EditWorkTimeDlg').modal({ show: false });
        var url = '@Url.Action( "Index", "WorkTimes")';                    
        window.location.href = url;
    }
    function OnFailureDetails(data) {
        
        alert( "Error: '" + data.statusText + "'" );
    }

    function OnEditWorkTime(id) {

        $.ajax({
            url: '@Url.Action( "Details", "WorkTimes" )',
            type: 'POST',
            data: JSON.stringify({ id: id }),
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                $('#dialogContent').html(data);
                $('#EditWorkTimeDlg').modal({ show: true });
            },
            error: function (data) {

                alert("Error: '" + data.statusText + "'");
            }
        });
    }

    function OnDeleteWorkTime(id) {
        $.ajax({
            url: '@Url.Action( "DeleteWorkTimeById", "WorkTimes" )',
            type: 'POST',
            data: JSON.stringify({ id: id }),
            contentType: 'application/json; charset=utf-8',
            success: function (data) {

                var url = '@Url.Action( "Index", "WorkTimes")';                    
                window.location.href = url;

            },
            error: function (data) {

                alert("Error: '" + data.statusText + "'");

            }
        });
    }

</script>
<style type="text/css">
</style>
@{
    var grid = new WebGrid(source: Model.WorkTimes, canPage: true, defaultSort: "Id", rowsPerPage: 100, canSort: true);
}

<div class="row">
    <div class="col-md-4">
        <h2>Work times</h2>

        <div id="gridContent" style="padding-right: 40%;">
            @grid.GetHtml(
           tableStyle: "table",
           fillEmptyRows: false,
           alternatingRowStyle: "alt",
           headerStyle: "thead-dark",
           footerStyle: "foot-grid",
           mode: WebGridPagerModes.All,
           firstText: "<< First",
           previousText: " < Previous",
           nextText: "Next >",
           lastText: "Last >>",
           caption: "",
           emptyRowCellValue: null,
           columns:
            grid.Columns(
                grid.Column( "Name", "Name", format: @<text><label id="lbName">@item.Name</label></text> ),
                  grid.Column( "Start time", "StartTime", format: @<text><label id="lbName">@item.StartTime.ToString()</label></text> ),
                 grid.Column( "End time", "EndTime", format: @<text><label id="lbName">@item.EndTIme.ToString()</label></text> ),
                 grid.Column( "Week days", "WeekDays", format: @<text><label id="lbName">@item.WeekDays.StringSelectedDays</label></text> ),
               grid.Column( "Action", format: @<text>
                <button onclick="OnEditWorkTime( @item.Id )" class="btn">Edit</button>
                <button onclick="OnDeleteWorkTime( @item.Id )" class="btn"> Delete</button>
            </text>, canSort: false )
       ) )
        </div>

        <button id="CreateConfig" onclick="OnEditWorkTime(0)" class="btn">Create</button>

        <div id="EditWorkTimeDlg" class="modal fade">
            <div id="dialogContent" class="modal-dialog" style="width:50%;"></div>
        </div>

    </div>
</div>   