NuntiusConfig/Controllers/ConfigurationsController.cs
using OPCConfigModel.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NuntiusConfig.Models;

namespace NuntiusConfig.Controllers
{
    public class ConfigurationsController : Controller
    {
        // GET: Configurations
        public ActionResult Index()
        {            

            return View( new ConfigurationsModel() );         
        }

        /// <summary>
        /// Details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details( Int32 id )
        {
            try
            {
                var model = ConfigMVC.Create( id );

                return PartialView( model );

            }
            catch( Exception ex )
            {
                TempData["ErrorModel"] = new ErrorModel( ex );
                return RedirectToAction( "Index", "Error" );
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public HttpStatusCodeResult UpdateConfiguration( ConfigMVC obj )
        {
            try
            {
                obj.SaveToBBDD();
                Session["NeedRestartService"] = true;

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            catch( Exception ex )
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public HttpStatusCodeResult DeleteConfigById( Int32 id )
        {
            try
            {

                ConfigMVC.DeleteById( id );

                Session["NeedRestartService"] = true;

                return new HttpStatusCodeResult(HttpStatusCode.OK);

            }
            catch( Exception ex )
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, ex.Message);
            }
        }
    }
}

NuntiusConfig/Views/Configurations/Details.cshtml
@model NuntiusConfig.Models.ConfigMVC
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>


@{Html.EnableClientValidation(true);}


@using (Ajax.BeginForm("UpdateConfiguration", "Configurations",
                    new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccessDlgDetails", OnFailure = "OnFailureDlgDetails" }))
{
    @Html.AntiForgeryToken()


    <div class="modal-content">
        <div class="modal-header">
            <h4>Configuration</h4>
            <button class="close" data-dismiss="modal" area-hidden="true">X</button>

        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                @Html.ValidationSummary(true)

                @Html.HiddenFor(model => model.Id)

                <div class="editor-label">
                    <dt>Name:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    <dt>Active:</dt>
                </div>
                <div class="editor-field">
                    @Html.CheckBoxFor(model => model.Active)
                </div>

                <div class="editor-label">
                    <dt>Visible:</dt>
                </div>
                <div class="editor-field">
                    @Html.CheckBoxFor(model => model.Visible)
                </div>

                <div class="editor-label">
                    <dt>Timeout:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Timeout)
                    @Html.ValidationMessageFor(model => model.Timeout)
                </div>

                <div class="editor-label">
                    <dt>Alarm detected:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.AlarmDetected)
                    @Html.ValidationMessageFor(model => model.AlarmDetected)
                </div>

                <div class="editor-label">
                    <dt>Publishing interval:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.PublishingInterval)
                    @Html.ValidationMessageFor(model => model.PublishingInterval)
                </div>

                <div class="editor-label">
                    <dt>Sampling interval:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.SamplingInterval)
                    @Html.ValidationMessageFor(model => model.SamplingInterval)
                </div>

                <div class="editor-label">
                    <dt>Queue size:</dt>
                </div>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.QueueSize)
                    @Html.ValidationMessageFor(model => model.QueueSize)
                </div>

                @*<div class="editor-label">
                            <dt>Groups:</dt>
                        </div>
                        <div class="editor-field">
                            @Html.CheckBoxListFor( model => model.Groups.Posted,
                                                   model => model.Groups.AllItems,
                                                   entity => entity.Value,
                                                   entity => entity.Text,
                                                   model => model.Groups.Selected,
                                                   MvcCheckBoxList.Model.Position.Vertical )
                    </div>*@

            </dl>
            <div class="modal-footer">
                <p><input type="submit" value="Save" /></p>
            </div>
        </div>
    </div>
}

NuntiusConfig/Views/Configurations/Index.cshtml
@model NuntiusConfig.Models.ConfigurationsModel

@{
}

<script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
<link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.min.css")">
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>



<script type="text/javascript">

    function OnSuccessDlgDetails(data) {

        $('#EditConfigurationDlg').modal({ show: false });
        var url = '@Url.Action( "Index", "Configurations")';
        window.location.href = url;
    }
    function OnFailureDlgDetails(data) {

        alert( "Error: '" + data.statusText + "'" );
    }

    function OnEditConfig( id )
    {
        $.ajax({
            url: '@Url.Action("Details", "Configurations")',
            data: JSON.stringify({ id: parseInt(id) }),
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            success: function (data) {

                $('#dialogContent').html(data);
                $('#EditConfigurationDlg').modal({ show: true });

            },
            error: function (data) {

                alert("Error: '" + data.statusText + "'");

            }
        });
    }

    function OnDeleteConfig(id) {
        $.ajax({
            url: '@Url.Action("DeleteConfigById", "Configurations")',
            data: JSON.stringify({ id: parseInt(id) }),
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            success: function (data)
            {

                window.location.href = '@Url.Action( "Index", "Configurations" )';

            },
            error: function (data) {

                alert("Error: '" + data.statusText + "'");
            }
        });
    }

</script>
<style type="text/css">
</style>
@{
    var grid = new WebGrid( source: Model.Configurations, canPage: true, defaultSort: "Id", rowsPerPage: 100, canSort: true );
}

<div class="row">
    <div class="col-md-4">        
        <h2>Configurations</h2>

        <br />
        <div id="gridContent" style="padding-right: 60%;">
            @grid.GetHtml(
                 tableStyle: "table",
                 fillEmptyRows: false,
                 alternatingRowStyle: "alt",
                 headerStyle: "thead-dark",
                 footerStyle: "foot-grid",
                 mode: WebGridPagerModes.All,
                 firstText: "<< First",
                 previousText: " < Previous",
                 nextText: "Next >",
                 lastText: "Last >>",
                 caption: "",
                 emptyRowCellValue: null,
            columns:
                grid.Columns(
                grid.Column( "Name", "Name", format: @<text><label id="lbName">@item.Name</label></text> ),
                           grid.Column( "Status", "Status", format: @<text><label id="lbName">@( item.Active ? "Active" : "No active")</label></text> ),
                          grid.Column( "Visible", "Visible", format: @<text><label id="lbName">@( item.Visible ? "Visible" : "No visible")</label></text> ),

                                     grid.Column( "Action", format: @<text>
                                        <button onclick="OnEditConfig( @item.Id )" class="btn">Edit</button>
                                        <button onclick="OnDeleteConfig( @item.Id )" class="btn"> Delete</button>
                                    </text>, canSort: false )
                                                                                                     ) )
        </div>
        <button id="CreateConfig" onclick="OnEditConfig(0)" class="btn">Create</button>

        <div id="EditConfigurationDlg" class="modal fade">
            <div id="dialogContent" class="modal-dialog" style="width:50%"></div>
        </div>

    </div>
</div>