NuntiusConfig/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NuntiusConfig.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

NuntiusConfig/Controllers/OPCItemsController.cs
using NuntiusConfig.Models;
using OPCConfigModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace NuntiusConfig.Controllers
{
    public class OPCItemsController : Controller
    {
        // GET: OPCItems
        public ActionResult Index()
        {
            return View( "Index", OPCItemsModel.CreateFromBBDD() );
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public  ActionResult LoadItems( OPCItemsModel obj )
        {
            OPCItemsModel m =(OPCItemsModel)obj;

            try
            {
                obj.FileToBBDD();
                
                Session["NeedRestartService"] = true;

                return View( "Index", OPCItemsModel.CreateFromBBDD() );
                //return new HttpStatusCodeResult( HttpStatusCode.OK );
            }
            catch( Exception ex )
            {
                TempData["ErrorModel"] = new ErrorModel( ex);
                return RedirectToAction( "Index", "Error" );
               // return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, ex.Message );
            }            
        }        

    }
}

NuntiusConfig/Controllers/ServiceController.cs
using NuntiusConfig.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NuntiusConfig.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        public ActionResult Index()
        {
            try
            {

                ServiceModel model = new ServiceModel();

                model.LoadFromBBDD();
            
                return View( model );
                
            }
            catch( Exception ex )
            {
                TempData["ErrorModel"] = new ErrorModel( ex);
                return RedirectToAction( "Index", "Error" );
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public ActionResult UpdateService( ServiceModel obj )
        {
            try
            {
                obj.SaveToBBDD();
                
                Session["NeedRestartService"] = true;

                return View( "Index" );
            }
            catch( Exception ex )
            {
                TempData["ErrorModel"] = new ErrorModel( ex );
                return RedirectToAction( "Index", "Error" );
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public HttpStatusCodeResult UpdateSMTP( SMTPConfigMVC obj )
        {
            try
            {
                obj.SaveToBBDD();
                
                Session["NeedRestartService"] = true;

                return new HttpStatusCodeResult( HttpStatusCode.OK );

            } catch( Exception ex )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, ex.Message );
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult DetailsSMTP()
        {
            try
            {
                return PartialView( SMTPConfigMVC.LoadFromBBDD() );


            } catch( Exception ex )
            {
                TempData["ErrorModel"] = new ErrorModel( ex );
                return RedirectToAction( "Index", "Error" );
            }
        }

        /// <summary>
        /// Self test
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public HttpStatusCodeResult SMTPTest( SMTPConfigMVC obj )
        {
            try
            {
                obj.TestConfig();

                return new HttpStatusCodeResult( HttpStatusCode.OK );

            } catch( Exception ex )
            {
                StringBuilder sb = new StringBuilder();

                sb.Append( ex.Message );

                if( ex.InnerException != null )
                {
                    sb.Append( ":" );
                    sb.Append( ex.InnerException.Message );
                }

                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, sb.ToString() );
            }
        }
    }
}

NuntiusConfig/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NuntiusConfig/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NuntiusConfig/Views/Home/Index.cshtml
@{    
}
<div class="container">
    <div class="row">
        <div>
            @*<h2 style="float: right; padding-right: 40%;">*@
            @Html.ActionLink( "Configurations", "Index", "Configurations" )
            </br>
            @Html.ActionLink( "Work times", "Index", "WorkTimes" )
            </br>
            @Html.ActionLink( "Messages saltos", "Index", "EventSaverConfig" )
            </br>
            @Html.ActionLink( "Users", "Index", "Users" )
            </br>
            @Html.ActionLink( "Groups", "Index", "Groups" )
            </br>
            @Html.ActionLink( "Load OPC UA items", "Index", "OPCItems" )
            </br>
            @Html.ActionLink( "Aqualogy OPC Service", "Index", "Service" )
            </br>
            @Html.ActionLink( "WCF Aqualogy OPC Service", "Index", "WCFService" )
            @*</h2>*@
        </div>
    </div>
</div>