NuntiusConfig/Controllers/WCFServiceController.cs
using NuntiusConfig.AqualogyOPCWCFService;
using NuntiusConfig.Models;
using System;
using System.Net;
using System.ServiceModel;
using System.Web.Mvc;

namespace NuntiusConfig.Controllers
{
    public class WCFServiceController : Controller
    {
        // GET: WCFService
        public ActionResult Index()
        {
            return View( new ConfigurationsStatesModel() );
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public HttpStatusCodeResult Start()
        {
            try
            {

                ConfigurationsStatesModel.SendCommand( ConfigurationsStatesModel.eCommand.Start );

                Session["NeedRestartService"] = false;

                return new HttpStatusCodeResult( HttpStatusCode.OK );                

            } catch( FaultException<AqualogyOPCRestServiceFault> faultEx )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, faultEx.Detail.CustomError );

            }catch( Exception ex )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, ex.Message );
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public HttpStatusCodeResult Stop()
        {
            try
            {

                ConfigurationsStatesModel.SendCommand( ConfigurationsStatesModel.eCommand.Stop );
                
                Session["NeedRestartService"] = false;

                return new HttpStatusCodeResult( HttpStatusCode.OK );

            }
            catch( FaultException<AqualogyOPCRestServiceFault> faultEx )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, faultEx.Detail.CustomError );

            } catch( Exception ex )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, ex.Message );
            }

        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public HttpStatusCodeResult Restart()
        {
            try
            {

                ConfigurationsStatesModel.SendCommand( ConfigurationsStatesModel.eCommand.Restart );

                Session["NeedRestartService"] = false;

                return new HttpStatusCodeResult( HttpStatusCode.OK );

            }catch( FaultException<AqualogyOPCRestServiceFault> faultEx )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, faultEx.Detail.CustomError );

            }catch( Exception ex )
            {
                return new HttpStatusCodeResult( HttpStatusCode.InternalServerError, ex.Message );
            }
        }
    }
}

NuntiusConfig/Views/WCFService/Index.cshtml
@model NuntiusConfig.Models.ConfigurationsStatesModel


<script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")"></script>
<link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.min.css")">
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

<script type="text/javascript">


    function StopOPCWCFService()
    {
        $.ajax({
            url: '@Url.Action( "Stop", "WCFService" )',
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            success: function (data) {

                alert('Stop OPC service OK!');
                var url = '@Url.Action( "Index", "WCFService" )';
                window.location.href = url;
            },
            error: function (data) {

                alert(data.statusText);
                var url = '@Url.Action( "Index", "WCFService" )';
                window.location.href = url;

            }
        });
    }

    function StartOPCWCFService()
    {
        $.ajax({
            url: '@Url.Action( "Start", "WCFService" )',
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            success: function (data) {

                alert('Start OPC service OK!');
                var url = '@Url.Action( "Index", "WCFService" )';
                window.location.href = url;
            },
            error: function (data) {

                alert(data.statusText);
                var url = '@Url.Action( "Index", "WCFService" )';
                window.location.href = url;

            }
        });
    }

    function RestartOPCWCFService()
    {
        $.ajax({
            url: '@Url.Action( "Restart", "WCFService" )',
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            success: function (data) {

                alert('Restart OPC service OK!');
                var url = '@Url.Action( "Index", "WCFService" )';
                window.location.href = url;
            },
            error: function (data) {

                alert(data.statusText);
                var url = '@Url.Action( "Index", "WCFService" )';
                window.location.href = url;
            }
        });
    }

</script>

<div class="row">
    <div class="col-md-4">
        <h2>Windows service </h2>

        @helper OPCConfigurations( IEnumerable<SelectListItem> configs )
        {
            <ul>
                @foreach( SelectListItem config in configs )
                {
                    <li style=@( config.Selected ? "background:green": "background:rosybrown")>@config.Text</li>
                }
            </ul>
        }

        @OPCConfigurations( Model.Configurations.AllItems )

        <button onclick="StopOPCWCFService();return false;" class="btn">Stop</button>
        <button onclick="StartOPCWCFService();return false;" class="btn">Start</button>
        <button onclick="RestartOPCWCFService();return false;" class="btn">Restart</button>
    </div>
</div>